"""Regression tests for issue #1063.

Bug: ``checkup``/auto-heal can patch generated PDD code without updating the
source prompt, producing prompt/code drift in a bot-authored fix PR.

Background — PR promptdriven/pdd#1055
=====================================

The bot commit ``bf57242d9a18072f3d444f91d9a834ba067f15ca`` changed *only*
``pdd/agentic_update.py``.  Before the commit the prompt source
``pdd/prompts/agentic_update_python.prompt`` specified

    _compute_include_allowlist(prompt_path: Path, *, max_depth: int = 3) -> set[Path]
    ...
    cap recursion at max_depth levels

The bot rewrote the generated code to drop ``max_depth`` and traverse without a
depth cap, but did not touch the prompt.  For ~14 minutes the PR HEAD therefore
contained code that contradicted its prompt contract — exactly the drift the
issue describes.  A follow-up bot commit (``3106e382``) eventually patched the
prompt by hand, but nothing in the checkup/auto-heal pipeline *forced* that
follow-up.  The next ``pdd sync agentic_update`` could have overwritten the
direct code edit.

Acceptance criteria from the issue:

* "Add a regression where checkup fixer modifies a generated module whose prompt
  is present and registered in ``architecture.json``."
* "The workflow either updates the prompt and runs sync, or fails with a clear
  message requiring prompt-source changes."
* "A final drift check catches prompt/code contract divergence before marking
  checkup/auto-heal successful."

These tests assert the *expected* behaviour.  They are expected to FAIL on the
current (buggy) code because no such drift guard exists, and to PASS once the
fix lands.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Tuple
from unittest.mock import patch

import pytest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


PROMPT_WITH_MAX_DEPTH = """\
<pdd-reason>Test prompt for issue #1063 regression.</pdd-reason>

<pdd-interface>
{
  "type": "module",
  "module": {
    "functions": [
      {"name": "run_thing", "signature": "(x: int) -> int", "returns": "int"}
    ]
  }
}
</pdd-interface>

% Goal
Implement a helper ``_compute_include_allowlist(prompt_path: Path, *, max_depth: int = 3) -> set[Path]``
that performs a depth-bounded BFS over ``<include>`` references.  The helper
MUST cap recursion at ``max_depth`` levels.
"""


CODE_MATCHING_PROMPT = '''\
"""Generated by PDD from the test prompt."""

from pathlib import Path
from typing import Set


def run_thing(x: int) -> int:
    return x + 1


def _compute_include_allowlist(prompt_path: Path, *, max_depth: int = 3) -> Set[Path]:
    """Depth-bounded, cycle-safe BFS over <include> references."""
    # Real impl elided for the regression test.
    return set()
'''


CODE_DRIFTED_FROM_PROMPT = '''\
"""Generated by PDD from the test prompt — mutated by a hypothetical fixer."""

from pathlib import Path
from typing import Set


def run_thing(x: int) -> int:
    return x + 1


def _compute_include_allowlist(prompt_path: Path) -> Set[Path]:
    """Cycle-safe BFS over <include> references (no depth cap)."""
    return set()
'''


ARCH_ENTRY = {
    "filename": "mymod_python.prompt",
    "filepath": "pdd/mymod.py",
    "language": "Python",
    "reason": "Test module for issue #1063.",
    "description": "Toy module used to reproduce prompt/code drift.",
}


def _init_repo(root: Path) -> None:
    """Initialise a tiny git repo with the prompt/code/architecture layout."""
    (root / "pdd").mkdir(parents=True, exist_ok=True)
    (root / "pdd" / "prompts").mkdir(parents=True, exist_ok=True)

    (root / "pdd" / "prompts" / "mymod_python.prompt").write_text(
        PROMPT_WITH_MAX_DEPTH, encoding="utf-8"
    )
    (root / "pdd" / "mymod.py").write_text(CODE_MATCHING_PROMPT, encoding="utf-8")
    (root / "architecture.json").write_text(
        json.dumps([ARCH_ENTRY], indent=2), encoding="utf-8"
    )

    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "add", "-A"],
        cwd=root,
        check=True,
    )
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "-m", "init"],
        cwd=root,
        check=True,
    )


def _simulate_fixer_code_only_edit(root: Path) -> Tuple[Path, Path]:
    """Mirror the bf57242 scenario: fixer rewrites generated code, leaves prompt alone."""
    code_path = root / "pdd" / "mymod.py"
    prompt_path = root / "pdd" / "prompts" / "mymod_python.prompt"
    code_path.write_text(CODE_DRIFTED_FROM_PROMPT, encoding="utf-8")
    return prompt_path, code_path


def _pr_metadata() -> dict:
    """Stable PR metadata used by `_commit_and_push_if_changed` tests."""
    return {
        "clone_url": "https://example.invalid/repo.git",
        "head_ref": "feature/test",
        "head_owner": "owner",
        "head_repo": "repo",
    }


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_commit_and_push_refuses_code_only_edit_when_prompt_is_registered(tmp_path: Path):
    """Bot fixer commits that touch a prompt-backed module without touching the
    matching prompt MUST be refused.

    This mirrors the bf57242 scenario from PR #1055: only ``pdd/mymod.py``
    changes, while ``pdd/prompts/mymod_python.prompt`` (registered in
    ``architecture.json``) remains untouched.  The current
    ``_commit_and_push_if_changed`` flow has no awareness of
    ``architecture.json`` and will happily push the code-only commit.
    """
    from pdd.checkup_review_loop import _commit_and_push_if_changed

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)
    _simulate_fixer_code_only_edit(repo)

    # Mock the push helper so the test does not hit the network.  If the drift
    # guard works correctly, ``push_with_retry`` must never be called for this
    # worktree — we'll assert that below.
    with patch(
        "pdd.checkup_review_loop.push_with_retry",
        return_value=(True, ""),
    ) as mock_push:
        ok, message = _commit_and_push_if_changed(
            repo, _pr_metadata(), "fix: drift-introducing change"
        )

    assert not ok, (
        "Code-only edit to a prompt-backed module must be refused by "
        "_commit_and_push_if_changed. Got success with message: %r" % message
    )
    assert "prompt" in message.lower(), (
        "Failure message must explain that the prompt source needs updating. "
        f"Got: {message!r}"
    )
    # Drift must be refused before the push helper runs — otherwise the bot
    # would still write the drifted commit to the PR branch.
    mock_push.assert_not_called()


def test_drift_guard_flags_prompt_backed_module_with_only_code_changes(tmp_path: Path):
    """A standalone drift check should report the offending modules.

    Independent of how the guard is wired into the commit/push flow, the
    project should expose a pure function that, given a worktree, returns the
    set of prompt-backed modules whose generated code changed without a
    corresponding prompt change.  This locks down the public contract the
    acceptance criteria require.
    """
    import pdd.checkup_review_loop as crl

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)
    _simulate_fixer_code_only_edit(repo)

    # Resolve the guard regardless of which exact name the fix introduces.
    guard = None
    for name in (
        "verify_no_prompt_code_drift",
        "detect_prompt_code_drift",
        "check_prompt_code_drift",
    ):
        if hasattr(crl, name):
            guard = getattr(crl, name)
            break
    if guard is None:
        pytest.fail(
            "No prompt/code drift guard is exported from "
            "pdd.checkup_review_loop. See issue #1063."
        )

    result = guard(repo)  # type: ignore[misc]

    # The guard may return either a boolean (False == drift detected) or a
    # collection of offending paths/modules.  Either form must indicate drift.
    if isinstance(result, bool):
        assert result is False, (
            "Drift guard returned True (no drift) for a worktree that "
            "modified pdd/mymod.py without updating its prompt."
        )
    else:
        offenders = list(result) if result is not None else []
        assert offenders, (
            "Drift guard returned an empty/None result for a worktree that "
            "modified pdd/mymod.py without updating its prompt."
        )
        joined = " ".join(str(o) for o in offenders)
        assert "mymod" in joined, (
            "Drift guard did not flag pdd/mymod.py as drifting. "
            f"Reported offenders: {offenders!r}"
        )


# ---------------------------------------------------------------------------
# Step 9 additions — Step 8 plan items 2, 3, 5, 6.
#
# These tests round out the drift-guard contract.  All four exercise observable
# behaviour of ``_commit_and_push_if_changed``: each invocation either makes
# it to ``push_with_retry`` (no drift) or short-circuits before reaching it
# (drift refused / nothing to push).  We mock the push helper so the test
# does not hit the network, and so we can assert the caller actually reached
# the push site when we expect it to.
# ---------------------------------------------------------------------------


def test_commit_and_push_allows_paired_prompt_and_code_edit(tmp_path: Path):
    """Fix that updates BOTH the prompt and the generated code must succeed.

    False-positive ward: the drift guard added for issue #1063 must not refuse
    the *correct* fix shape (prompt-source change + regenerated code).
    """
    from pdd.checkup_review_loop import _commit_and_push_if_changed

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    # Bot updated prompt AND regenerated code in the same commit (the
    # acceptance-criteria-compliant fix shape).
    (repo / "pdd" / "prompts" / "mymod_python.prompt").write_text(
        PROMPT_WITH_MAX_DEPTH.replace("max_depth: int = 3", "max_depth: int = 5"),
        encoding="utf-8",
    )
    (repo / "pdd" / "mymod.py").write_text(
        CODE_MATCHING_PROMPT.replace("max_depth: int = 3", "max_depth: int = 5"),
        encoding="utf-8",
    )

    with patch(
        "pdd.checkup_review_loop.push_with_retry",
        return_value=(True, ""),
    ) as mock_push:
        ok, message = _commit_and_push_if_changed(
            repo, _pr_metadata(), "fix: bump max_depth in prompt + regenerated code"
        )

    assert ok, (
        "Paired prompt+code edit must NOT be refused by the drift guard. "
        f"Got failure: {message!r}"
    )
    # The caller must actually invoke the push helper — proves we reached the
    # push site rather than short-circuiting silently.
    mock_push.assert_called_once()


def test_commit_and_push_allows_edit_to_non_prompt_backed_file(tmp_path: Path):
    """Edits to files NOT registered in architecture.json must pass the guard.

    No false-positives on documentation, CI config, tests, or other non-PDD
    artifacts.  This guards against an over-eager drift check that would
    refuse every commit.
    """
    from pdd.checkup_review_loop import _commit_and_push_if_changed

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    # Modify a tracked file that's not the prompt-backed module.  README is
    # not in architecture.json so the drift guard must ignore it.
    (repo / "README.md").write_text("# Project\n\nUpdated docs.\n", encoding="utf-8")
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t", "add", "README.md"],
        cwd=repo,
        check=True,
    )
    subprocess.run(
        ["git", "-c", "user.email=t@t", "-c", "user.name=t",
         "commit", "-q", "-m", "seed README"],
        cwd=repo,
        check=True,
    )
    # Now actually mutate it so there's a diff to commit.
    (repo / "README.md").write_text("# Project\n\nUpdated docs again.\n", encoding="utf-8")

    with patch(
        "pdd.checkup_review_loop.push_with_retry",
        return_value=(True, ""),
    ) as mock_push:
        ok, message = _commit_and_push_if_changed(
            repo, _pr_metadata(), "docs: update README"
        )

    assert ok, (
        "Edit to a non-prompt-backed file (README.md) must not be refused. "
        f"Got failure: {message!r}"
    )
    mock_push.assert_called_once()


def test_commit_and_push_refuses_newly_added_prompt_backed_code(tmp_path: Path):
    """Drift guard must catch NEW files too, not only modifications.

    A fixer that *adds* a generated module without authoring the corresponding
    prompt would otherwise slip through a diff-based guard.  The acceptance
    criteria explicitly demand consistency between prompt source and generated
    code regardless of whether the code is new or modified.
    """
    from pdd.checkup_review_loop import _commit_and_push_if_changed

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    # Register a SECOND prompt-backed module in architecture.json but only
    # create the generated code file — no prompt source.  This is exactly
    # the drift the guard must catch on newly added paths.
    arch_path = repo / "architecture.json"
    entries = json.loads(arch_path.read_text(encoding="utf-8"))
    entries.append(
        {
            "filename": "newmod_python.prompt",
            "filepath": "pdd/newmod.py",
            "language": "Python",
            "reason": "Newly added module for issue #1063 regression.",
            "description": "Brand-new prompt-backed module with no prompt source.",
        }
    )
    arch_path.write_text(json.dumps(entries, indent=2), encoding="utf-8")
    (repo / "pdd" / "newmod.py").write_text(
        '"""Newly authored generated code without a prompt source."""\n\n'
        "def foo() -> int:\n    return 1\n",
        encoding="utf-8",
    )

    with patch(
        "pdd.checkup_review_loop.push_with_retry",
        return_value=(True, ""),
    ) as mock_push:
        ok, message = _commit_and_push_if_changed(
            repo, _pr_metadata(), "feat: add newmod (forgot the prompt)"
        )

    assert not ok, (
        "Adding a prompt-backed module without authoring its prompt must be "
        f"refused. Got success with message: {message!r}"
    )
    assert "prompt" in message.lower(), (
        "Failure message must call out the missing prompt source. "
        f"Got: {message!r}"
    )
    # If the guard refused before push, push_with_retry must not have run.
    mock_push.assert_not_called()


def test_commit_and_push_ignores_only_pdd_meta_artifact_changes(tmp_path: Path):
    """Drift guard must not trip on PDD's own meta artifacts.

    ``.pdd/meta/*.json`` files are intentionally filtered out of the staging
    step (see ``_is_untracked_pdd_meta_artifact``).  If the *only* change in
    the worktree is such a meta artifact, the commit/push helper must return
    cleanly without raising a drift error — there is no prompt-backed code
    change to validate.
    """
    from pdd.checkup_review_loop import _commit_and_push_if_changed

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)

    # Only change is an untracked PDD meta artifact.
    meta_dir = repo / ".pdd" / "meta"
    meta_dir.mkdir(parents=True, exist_ok=True)
    (meta_dir / "scratch.json").write_text(
        json.dumps({"scratch": True}), encoding="utf-8"
    )

    with patch(
        "pdd.checkup_review_loop.push_with_retry",
        return_value=(True, ""),
    ) as mock_push:
        ok, message = _commit_and_push_if_changed(
            repo, _pr_metadata(), "chore: scratch meta artifact"
        )

    # Either no eligible changes (nothing to stage after filter) or a successful
    # push — both are acceptable.  What must NOT happen is a drift-style refusal.
    assert ok, (
        "Meta-artifact-only worktree must not be refused by the drift guard. "
        f"Got failure: {message!r}"
    )
    assert "prompt" not in message.lower(), (
        "No prompt should be mentioned when the only change is a PDD meta "
        f"artifact. Got: {message!r}"
    )
    # Should not have actually pushed anything since the meta file is filtered.
    mock_push.assert_not_called()


# ---------------------------------------------------------------------------
# Step 9 addition — direct coverage of the callee module ``pdd/prompt_drift_guard.py``.
#
# Per Step 6, the drift-guard helper lives in a new module
# ``pdd.prompt_drift_guard`` and is re-exported from ``pdd.checkup_review_loop``.
# The other tests in this file exercise the caller side (via
# ``_commit_and_push_if_changed`` or via ``pdd.checkup_review_loop``'s re-export).
# This test exercises the callee module *directly* — i.e. it imports
# ``pdd.prompt_drift_guard`` and calls its public helper.  Without this, the
# fix could land in checkup_review_loop alone and silently sidestep the
# planned module split.
# ---------------------------------------------------------------------------


def test_prompt_drift_guard_module_detects_code_only_edit(tmp_path: Path):
    """The standalone ``pdd.prompt_drift_guard`` module must flag drift.

    Per Step 6, the guard helper lives in its own module so it can be reused
    independently of the commit/push path.  This test imports that module
    directly and asserts behaviour on a worktree mirroring the bf57242
    scenario: a prompt-backed module's code has changed without a matching
    prompt change.

    Expected to FAIL on current code (module does not exist yet) and PASS
    once ``pdd/prompt_drift_guard.py`` is added with the documented helper.
    """
    # Import lazily so pytest's collection error message is clear.
    try:
        import pdd.prompt_drift_guard as guard_mod
    except ImportError as exc:  # pragma: no cover - failure path
        pytest.fail(
            "pdd.prompt_drift_guard module must exist as a standalone callee "
            f"(see issue #1063 and Step 6 plan). Import failed: {exc!r}"
        )

    repo = tmp_path / "repo"
    repo.mkdir()
    _init_repo(repo)
    _simulate_fixer_code_only_edit(repo)

    # The exact public symbol name is locked down here.  Any of the names
    # discussed in the Step 6 plan satisfies the contract — pick the first
    # one the module actually exposes.
    candidates = (
        "detect_prompt_code_drift",
        "verify_no_prompt_code_drift",
        "check_prompt_code_drift",
        "find_prompt_code_drift",
    )
    guard = None
    for name in candidates:
        if hasattr(guard_mod, name):
            guard = getattr(guard_mod, name)
            break
    assert guard is not None, (
        "pdd.prompt_drift_guard must expose a public helper. "
        f"Tried {candidates!r}. See issue #1063."
    )

    result = guard(repo)

    # The helper may return either a boolean drift-flag (False == no drift)
    # or a collection of offending paths/module names.  Both shapes are
    # acceptable; either way the result must clearly indicate drift on this
    # worktree.
    if isinstance(result, bool):
        assert result is True, (
            "Drift helper returned False (no drift) for a worktree that "
            "modified pdd/mymod.py without updating its prompt."
        )
    else:
        offenders = list(result) if result is not None else []
        assert offenders, (
            "Drift helper returned an empty/None result for a worktree that "
            "modified pdd/mymod.py without updating its prompt."
        )
        joined = " ".join(str(o) for o in offenders)
        assert "mymod" in joined, (
            "Drift helper did not flag pdd/mymod.py as drifting. "
            f"Reported offenders: {offenders!r}"
        )
