"""Canonical, side-effect-free primitives for global synchronization."""

from .classifier import classify
from .capabilities import CapabilityError, CapabilityRegistry, CommandCapability
from .certificate import (
    CheckerIdentity,
    GlobalCertificateOptions,
    LifecycleResult,
    NightlyObservation,
    RemoteCertificateSigner,
    RepositoryTarget,
    build_global_certificate,
    count_vendored_sync_semantics,
    checker_identity_from_environment,
    signer_from_environment,
    verify_global_certificate,
)
from .artifact_provenance import (
    CandidateArtifactPolicy,
    CandidateArtifactProvenance,
    CandidateArtifactProvenanceError,
    candidate_artifact_policy_from_environment,
    load_candidate_artifact_provenance,
)
from .identity import (
    RepositoryIdentity,
    RepositoryIdentityError,
    canonical_repository_id,
    initialize_repository_identity,
    read_repository_identity,
)
from .human_attestation import (
    HumanAttestationError,
    HumanAttestationPolicy,
    HumanAttestationRequest,
    HumanAttestationVerifier,
    load_human_attestation_policy,
)
from .fingerprint_store import (
    CorruptFingerprintError,
    FingerprintStore,
    FingerprintStoreError,
    LegacyFingerprintRecord,
    encode_fingerprint,
)
from .finalize import (
    CanonicalFinalizationError,
    FinalizeResult,
    attestation_signer_from_environment,
    canonical_root_for_paths,
    finalize_legacy_paths,
    protected_runner_config_from_environment,
    finalize_unit,
)
from .evidence_store import (
    EvidenceStoreError,
    LoadedTrustPolicy,
    decode_attestation,
    encode_attestation,
    evidence_relpath,
    load_attestation,
    load_trust_policy,
)
from .includes import (
    IncludeClosure,
    IncludeEdge,
    IncludeGraphError,
    IncludeReference,
    IncludeSyntax,
    build_include_closure,
    include_paths,
    parse_include_references,
)
from .language import LanguageRegistry, LanguageRegistryError, LanguageSpec
from .lifecycle import run_lifecycle_matrix
from .manifest import (
    CandidateRecord,
    ManifestError,
    ManifestUnit,
    UnitManifest,
    build_unit_manifest,
)
from .path_policy import PathPolicy, PathPolicyError, ResolvedPath
from .planner import RepairAction, RepairPlan, RepairPolicy, plan_repair
from .snapshot import SnapshotError, build_unit_snapshot
from .reporting import (
    CanonicalCounts,
    CanonicalReportOptions,
    build_canonical_report,
)
from .runner import (
    AttestationIssue,
    RunBinding,
    RunnerConfig,
    RunnerExecution,
    TRUSTED_RUNNER_VERSION,
    run_obligation,
    run_profile,
    runner_identity_digest,
)
from .trust import (
    AttestationBinding,
    AttestationEnvelope,
    AttestationError,
    AttestationIssuer,
    AttestationRequest,
    AttestationSigner,
    RemoteAttestationSigner,
    AttestationTrustPolicy,
    FileReplayStore,
    InMemoryReplayStore,
    ValidationEvidence,
)
from .transaction import (
    PlannedWrite,
    RecoveryRequired,
    TransactionConflict,
    TransactionError,
    TransactionManager,
    TransactionPhase,
    TransactionResult,
)
from .verification import (
    ProfileSet,
    VerificationProfileError,
    load_verification_profiles,
)
from .waivers import SyncWaiver, WaiverSet, load_sync_waivers
from .types import (
    ArtifactSnapshot,
    BaselineStatus,
    CandidateId,
    EvidenceOutcome,
    FingerprintRecord,
    FingerprintProvenance,
    InventoryStatus,
    SemanticStatus,
    SyncVerdict,
    UnitId,
    UnitSnapshot,
    VerificationObligation,
    VerificationProfile,
)

__all__ = [
    "ArtifactSnapshot",
    "AttestationBinding",
    "AttestationEnvelope",
    "AttestationError",
    "AttestationIssuer",
    "AttestationIssue",
    "AttestationRequest",
    "AttestationSigner",
    "RemoteAttestationSigner",
    "AttestationTrustPolicy",
    "BaselineStatus",
    "CandidateId",
    "CandidateArtifactPolicy",
    "CandidateArtifactProvenance",
    "CandidateArtifactProvenanceError",
    "CandidateRecord",
    "CanonicalCounts",
    "CanonicalFinalizationError",
    "CanonicalReportOptions",
    "CapabilityError",
    "CapabilityRegistry",
    "CommandCapability",
    "CorruptFingerprintError",
    "EvidenceOutcome",
    "EvidenceStoreError",
    "FingerprintRecord",
    "FingerprintProvenance",
    "FingerprintStore",
    "FingerprintStoreError",
    "HumanAttestationError",
    "HumanAttestationPolicy",
    "HumanAttestationRequest",
    "HumanAttestationVerifier",
    "FileReplayStore",
    "FinalizeResult",
    "GlobalCertificateOptions",
    "IncludeReference",
    "IncludeSyntax",
    "IncludeClosure",
    "IncludeEdge",
    "IncludeGraphError",
    "InventoryStatus",
    "InMemoryReplayStore",
    "LanguageRegistry",
    "LanguageRegistryError",
    "LanguageSpec",
    "LegacyFingerprintRecord",
    "LoadedTrustPolicy",
    "LifecycleResult",
    "NightlyObservation",
    "RemoteCertificateSigner",
    "ManifestError",
    "ManifestUnit",
    "PathPolicy",
    "PathPolicyError",
    "PlannedWrite",
    "ProfileSet",
    "RecoveryRequired",
    "RepairAction",
    "RepairPlan",
    "RepairPolicy",
    "RunnerConfig",
    "RunnerExecution",
    "RunBinding",
    "RepositoryIdentity",
    "RepositoryIdentityError",
    "RepositoryTarget",
    "ResolvedPath",
    "SemanticStatus",
    "SnapshotError",
    "SyncVerdict",
    "SyncWaiver",
    "TransactionConflict",
    "TransactionError",
    "TransactionManager",
    "TransactionPhase",
    "TransactionResult",
    "TRUSTED_RUNNER_VERSION",
    "UnitId",
    "UnitManifest",
    "UnitSnapshot",
    "ValidationEvidence",
    "VerificationObligation",
    "VerificationProfile",
    "VerificationProfileError",
    "WaiverSet",
    "classify",
    "canonical_repository_id",
    "candidate_artifact_policy_from_environment",
    "canonical_root_for_paths",
    "decode_attestation",
    "encode_attestation",
    "encode_fingerprint",
    "evidence_relpath",
    "finalize_unit",
    "finalize_legacy_paths",
    "protected_runner_config_from_environment",
    "build_include_closure",
    "build_canonical_report",
    "build_global_certificate",
    "CheckerIdentity",
    "checker_identity_from_environment",
    "build_unit_manifest",
    "build_unit_snapshot",
    "attestation_signer_from_environment",
    "count_vendored_sync_semantics",
    "include_paths",
    "load_verification_profiles",
    "load_attestation",
    "load_candidate_artifact_provenance",
    "load_human_attestation_policy",
    "load_trust_policy",
    "load_sync_waivers",
    "initialize_repository_identity",
    "read_repository_identity",
    "run_obligation",
    "run_lifecycle_matrix",
    "run_profile",
    "runner_identity_digest",
    "signer_from_environment",
    "parse_include_references",
    "plan_repair",
    "verify_global_certificate",
]
