"""Setup configuration for pdd-cli."""

from setuptools import setup, find_packages

setup(
    name="pdd-cli",
    version="0.0.179",
    author="pdd-auto-heal[bot]",
    author_email="pdd-auto-heal[bot]@users.noreply.github.com",
    description="PDD (Prompt-Driven Development) - A toolkit for AI-powered code generation and maintenance",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/gltanaka/pdd",
    packages=find_packages(),
    include_package_data=True,
    package_data={
        "pdd": [
            "data/*.csv",
            "templates/**/*.prompt",
            "templates/**/*.md",
        ],
    },
    python_requires=">=3.8",
    install_requires=[
        "GitPython==3.1.44",
        "PyYAML==6.0.1",
        "Requests==2.32.4",
        "aiofiles==24.1.0",
        "boto3==1.35.99",
        "click==8.1.7",
        "firebase_admin==6.6.0",
        "firecrawl_py==2.5.3",
        "google-cloud-aiplatform>=1.3",
        "jsonschema==4.23.0",
        "keyring==25.6.0",
        "litellm[caching]>=1.80.0",
        "lxml>=5.0.0",
        "nest_asyncio==1.6.0",
        "openai>=1.99.5",
        "pandas==2.2.3",
        "pillow-heif==1.1.1",
        "Pillow==12.0.0",
        "psutil>=7.0.0",
        "pydantic==2.11.4",
        "python-dotenv==1.1.0",
        "rich==14.0.0",
        "semver==3.0.2",
        "setuptools",
        "textual",
        "z3_solver==4.14.1.0",
        # Server dependencies (for pdd connect)
        "fastapi>=0.115.0",
        "uvicorn[standard]>=0.32.0",
        "websockets>=13.0",
        "watchdog>=4.0.0",
        "tiktoken>=0.7.0",
    ],
    extras_require={
        "dev": [
            "build",
            "commitizen",
            "httpx==0.28.1",
            "pytest==8.3.5",
            "pytest-asyncio",
            "pytest-cov==5.0.0",
            "pytest-mock",
            "pytest-testmon",
            "pytest-xdist",
            "twine",
        ],
    },
    entry_points={
        "console_scripts": [
            "pdd=pdd.cli:cli",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Code Generators",
        "Topic :: Software Development :: Libraries :: Application Frameworks",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Operating System :: OS Independent",
    ],
    keywords="pdd prompt-driven-development ai code-generation cli llm",
    project_urls={
        "Bug Reports": "https://github.com/gltanaka/pdd/issues",
        "Source": "https://github.com/gltanaka/pdd",
        "Discord": "https://discord.gg/Yp4RTh8bG7",
    },
)