// example_usage.ts
// Comprehensive usage example for the composition generation pipeline API routes.
//
// This module provides three API endpoints for a video production pipeline:
//   1. POST /api/pipeline/compositions/run — Generates Remotion components via Claude Code
//   2. POST /api/pipeline/asset-staging/run — Copies Veo output assets to Remotion public dir
//   3. GET /api/pipeline/compositions/list — Lists all compositions with their status
//
// NOTE: These are Next.js Route Handlers (server-only). This example demonstrates
// how to call them from a client, how the SSE streaming works, and how the internal
// helpers function.

// ============================================================================
// Example 1: Calling POST /api/pipeline/compositions/run (SSE client)
// ============================================================================

/**
 * The POST /api/pipeline/compositions/run endpoint accepts a JSON body:
 *
 * @param body.components - string[] — Names of Remotion components to generate.
 *   Each name corresponds to a spec file in the `specs/` directory.
 *   Claude Code is invoked once per component with Read+Write+Edit+Glob tools
 *   scoped to `remotion/src/remotion/`.
 *
 * @param body.wrappers - string[] — Names of section wrapper compositions to generate.
 *   These are generated by running `python3 generate_section_compositions.py`.
 *
 * @returns An SSE (Server-Sent Events) stream with the following event types:
 *   - { type: 'component', name: string, status: 'generating' | 'done' | 'error' }
 *     Emitted per-component as generation progresses.
 *   - { type: 'job', jobId: string }
 *     Emitted once the pipeline stage job is created.
 *   - { type: 'complete', jobId: string }
 *     Emitted when all components and wrappers have been processed.
 *   - { type: 'error', message: string }
 *     Emitted if the pipeline stage fails.
 *   - { type: 'log', message: string, jobId: string }
 *     Emitted for each log line from Claude Code or the wrapper script.
 *   - { type: 'progress', percent: number, jobId: string }
 *     Emitted as components complete (percentage of total).
 */

async function example1_compositionsRun(): Promise<void> {
  console.log("=== Example 1: POST /api/pipeline/compositions/run ===\n");

  const requestBody = {
    components: ["IntroTitle", "BackgroundGradient", "LogoReveal"],
    wrappers: ["introWrapper", "IntroCompositionWrapper"],
  };

  console.log("Request body:", JSON.stringify(requestBody, null, 2));

  // In a real app, you'd fetch from the actual endpoint:
  //
  // const response = await fetch('/api/pipeline/compositions/run', {
  //   method: 'POST',
  //   headers: { 'Content-Type': 'application/json' },
  //   body: JSON.stringify(requestBody),
  // });
  //
  // The response is an SSE stream. Here's how to consume it:

  const sseConsumerCode = `
  const response = await fetch('/api/pipeline/compositions/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      components: ['IntroTitle', 'BackgroundGradient', 'LogoReveal'],
      wrappers: ['introWrapper'],
    }),
  });

  const reader = response.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\\\\n\\\\n');
    buffer = lines.pop() ?? '';

    for (const line of lines) {
      if (!line.startsWith('data: ')) continue;
      const event = JSON.parse(line.slice(6));

      switch (event.type) {
        case 'component':
          console.log(\\\`Component \\\${event.name}: \\\${event.status}\\\\\`);
          // 'generating' → Claude Code is working on it
          // 'done'       → Component file created successfully
          // 'error'      → Generation failed
          break;

        case 'progress':
          console.log(\\\`Progress: \\\${event.percent}%\\\\\`);
          break;

        case 'log':
          console.log(\\\`Log: \\\${event.message}\\\\\`);
          break;

        case 'job':
          console.log(\\\`Job created: \\\${event.jobId}\\\\\`);
          break;

        case 'complete':
          console.log(\\\`Pipeline complete. Job ID: \\\${event.jobId}\\\\\`);
          break;

        case 'error':
          console.error(\\\`Pipeline error: \\\${event.message}\\\\\`);
          break;
      }
    }
  }
  `;

  console.log("SSE consumer pattern (client-side):");
  console.log(sseConsumerCode);

  // Simulate the SSE events that would be emitted:
  const simulatedEvents = [
    { type: "component", name: "IntroTitle", status: "generating" },
    { type: "log", message: "[compositions] Generating component: IntroTitle", jobId: "job-abc-123" },
    { type: "component", name: "IntroTitle", status: "done" },
    { type: "progress", percent: 20, jobId: "job-abc-123" },
    { type: "component", name: "BackgroundGradient", status: "generating" },
    { type: "component", name: "BackgroundGradient", status: "done" },
    { type: "progress", percent: 40, jobId: "job-abc-123" },
    { type: "component", name: "LogoReveal", status: "generating" },
    { type: "component", name: "LogoReveal", status: "done" },
    { type: "progress", percent: 60, jobId: "job-abc-123" },
    { type: "component", name: "introWrapper", status: "generating" },
    { type: "component", name: "IntroCompositionWrapper", status: "generating" },
    { type: "component", name: "introWrapper", status: "done" },
    { type: "component", name: "IntroCompositionWrapper", status: "done" },
    { type: "progress", percent: 100, jobId: "job-abc-123" },
    { type: "job", jobId: "job-abc-123" },
    { type: "complete", jobId: "job-abc-123" },
  ];

  console.log("Simulated SSE event sequence:");
  for (const event of simulatedEvents) {
    console.log(`  data: ${JSON.stringify(event)}`);
  }
  console.log("");
}

// ============================================================================
// Example 2: Calling POST /api/pipeline/asset-staging/run
// ============================================================================

/**
 * The POST /api/pipeline/asset-staging/run endpoint copies generated video
 * assets from `outputs/veo/` to `remotion/public/` so Remotion can reference
 * them at build time.
 *
 * @param body.files - string[] (optional) — Specific file names to stage.
 *   If omitted or empty, the endpoint reads from a staging manifest file.
 *   Manifest lookup order:
 *     1. outputs/veo/staging.json
 *     2. outputs/veo/staging-manifest.json
 *     3. outputs/veo/manifest.json
 *   The manifest can be either a JSON array of filenames or an object
 *   with a `files` array property.
 *
 * @returns { jobId: string } — A UUID identifying this staging operation.
 *
 * Behavior:
 *   - For each file, copies from `outputs/veo/<file>` to `remotion/public/<file>`.
 *   - Creates intermediate directories as needed (recursive mkdir).
 *   - Skips files that don't exist in the source directory.
 *   - Skips files that already exist in the destination (no overwrite).
 */

async function example2_assetStaging(): Promise<void> {
  console.log("=== Example 2: POST /api/pipeline/asset-staging/run ===\n");

  // Option A: Specify files explicitly
  const explicitRequest = {
    files: [
      "intro/background.mp4",
      "intro/logo_reveal.mp4",
      "main/product_demo.mp4",
    ],
  };

  console.log("Request with explicit files:", JSON.stringify(explicitRequest, null, 2));

  // Option B: Let the endpoint read from the staging manifest
  const manifestRequest = {};

  console.log("Request using manifest (empty body):", JSON.stringify(manifestRequest));

  // Example manifest file (outputs/veo/staging.json):
  const exampleManifest = [
    "intro/background.mp4",
    "intro/logo_reveal.mp4",
    "main/product_demo.mp4",
    "outro/credits_bg.mp4",
  ];
  console.log("\nExample staging manifest:", JSON.stringify(exampleManifest, null, 2));

  // Alternative manifest format (outputs/veo/manifest.json):
  const altManifest = {
    files: ["intro/background.mp4", "main/product_demo.mp4"],
    generatedAt: "2025-01-15T10:00:00Z",
  };
  console.log("Alternative manifest format:", JSON.stringify(altManifest, null, 2));

  // Client-side usage:
  console.log("\nClient-side fetch pattern:");
  console.log(`
  // Stage specific files
  const response = await fetch('/api/pipeline/asset-staging/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      files: ['intro/background.mp4', 'main/product_demo.mp4'],
    }),
  });

  const { jobId } = await response.json();
  console.log('Asset staging job:', jobId);
  // => { jobId: "550e8400-e29b-41d4-a716-446655440000" }
  `);

  // Simulated response
  const simulatedResponse = { jobId: "550e8400-e29b-41d4-a716-446655440000" };
  console.log("Simulated response:", JSON.stringify(simulatedResponse));
  console.log("");
}

// ============================================================================
// Example 3: Calling GET /api/pipeline/compositions/list
// ============================================================================

/**
 * The GET /api/pipeline/compositions/list endpoint returns the status of all
 * compositions across all project sections.
 *
 * @returns { sections: CompositionSection[] }
 *
 * CompositionSection:
 *   @field sectionId  - string — The section ID from project.json (e.g., 'intro')
 *   @field components - CompositionEntry[] — Individual Remotion components for this section
 *   @field wrappers   - CompositionEntry[] — Section wrapper compositions
 *
 * CompositionEntry:
 *   @field name      - string — Component name (e.g., 'IntroTitle')
 *   @field status    - 'exists' | 'missing' | 'error'
 *     - 'exists'  — The .tsx file exists at remotion/src/remotion/<name>.tsx
 *     - 'missing' — The .tsx file does not exist yet
 *     - 'error'   — The last generation attempt for this component failed
 *   @field lastError - string | undefined — Error message from the last failed
 *     generation job (only present when status is 'error'). Retrieved from the
 *     SQLite jobs database by querying for the most recent 'compositions' stage
 *     job with status='error' whose params include this component name.
 *
 * How components are discovered:
 *   - Component names are derived from spec files in each section's specDir.
 *     All files in the specDir tree are walked; the basename (without extension)
 *     becomes the component name.
 *   - Wrapper names are derived from the section: `${section.id}Wrapper` and
 *     `${section.compositionId}Wrapper` (deduplicated).
 */

async function example3_compositionsList(): Promise<void> {
  console.log("=== Example 3: GET /api/pipeline/compositions/list ===\n");

  // Client-side usage:
  console.log("Client-side fetch pattern:");
  console.log(`
  const response = await fetch('/api/pipeline/compositions/list');
  const { sections } = await response.json();

  for (const section of sections) {
    console.log(\\\`Section: \\\${section.sectionId}\\\\\`);

    for (const comp of section.components) {
      const icon = comp.status === 'exists' ? '✅' : comp.status === 'error' ? '❌' : '⬜';
      console.log(\\\`  \\\${icon} \\\${comp.name} (\\\${comp.status})\\\\\`);
      if (comp.lastError) {
        console.log(\\\`     Error: \\\${comp.lastError}\\\\\`);
      }
    }

    for (const wrapper of section.wrappers) {
      const icon = wrapper.status === 'exists' ? '✅' : '⬜';
      console.log(\\\`  \\\${icon} \\\${wrapper.name} [wrapper] (\\\${wrapper.status})\\\\\`);
    }
  }
  `);

  // Simulated response matching the CompositionSection[] shape
  const simulatedResponse = {
    sections: [
      {
        sectionId: "intro",
        components: [
          { name: "IntroTitle", status: "exists" },
          { name: "BackgroundGradient", status: "exists" },
          { name: "LogoReveal", status: "missing" },
          {
            name: "ParticleEffect",
            status: "error",
            lastError: "Claude CLI timeout after 300s",
          },
        ],
        wrappers: [
          { name: "introWrapper", status: "exists" },
          { name: "IntroCompositionWrapper", status: "missing" },
        ],
      },
      {
        sectionId: "main",
        components: [
          { name: "ProductShowcase", status: "exists" },
          { name: "FeatureHighlight", status: "exists" },
          { name: "DemoAnimation", status: "missing" },
        ],
        wrappers: [
          { name: "mainWrapper", status: "exists" },
          { name: "MainCompositionWrapper", status: "exists" },
        ],
      },
      {
        sectionId: "outro",
        components: [
          { name: "CreditsRoll", status: "missing" },
          { name: "CallToAction", status: "missing" },
        ],
        wrappers: [
          { name: "outroWrapper", status: "missing" },
          { name: "OutroCompositionWrapper", status: "missing" },
        ],
      },
    ],
  };

  console.log("Simulated response:");
  console.log(JSON.stringify(simulatedResponse, null, 2));

  // Demonstrate how to use the response to determine what needs generation
  const missingComponents: string[] = [];
  const missingWrappers: string[] = [];
  const errorComponents: string[] = [];

  for (const section of simulatedResponse.sections) {
    for (const comp of section.components) {
      if (comp.status === "missing") missingComponents.push(comp.name);
      if (comp.status === "error") errorComponents.push(comp.name);
    }
    for (const wrapper of section.wrappers) {
      if (wrapper.status === "missing") missingWrappers.push(wrapper.name);
    }
  }

  console.log("\nComponents needing generation:", missingComponents);
  console.log("Components with errors (retry candidates):", errorComponents);
  console.log("Wrappers needing generation:", missingWrappers);
  console.log("");
}

// ============================================================================
// Example 4: Full workflow — List → Generate → Verify
// ============================================================================

/**
 * Demonstrates the typical end-to-end workflow:
 *   1. GET /api/pipeline/compositions/list to discover what's missing
 *   2. POST /api/pipeline/compositions/run to generate missing components
 *   3. GET /api/pipeline/compositions/list again to verify results
 *
 * This pattern is used by the pipeline editor UI to drive the compositions stage.
 */

async function example4_fullWorkflow(): Promise<void> {
  console.log("=== Example 4: Full Workflow (List → Generate → Verify) ===\n");

  console.log(`
  // Step 1: Discover what needs to be generated
  const listResponse = await fetch('/api/pipeline/compositions/list');
  const { sections } = await listResponse.json();

  // Collect missing and errored components across all sections
  const toGenerate: string[] = [];
  const wrappersToGenerate: string[] = [];

  for (const section of sections) {
    for (const comp of section.components) {
      if (comp.status === 'missing' || comp.status === 'error') {
        toGenerate.push(comp.name);
      }
    }
    for (const wrapper of section.wrappers) {
      if (wrapper.status === 'missing') {
        wrappersToGenerate.push(wrapper.name);
      }
    }
  }

  if (toGenerate.length === 0 && wrappersToGenerate.length === 0) {
    console.log('All compositions are up to date!');
    return;
  }

  // Step 2: Generate missing components via SSE stream
  console.log(\\\`Generating \\\${toGenerate.length} components and \\\${wrappersToGenerate.length} wrappers...\\\\\`);

  const runResponse = await fetch('/api/pipeline/compositions/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      components: toGenerate,
      wrappers: wrappersToGenerate,
    }),
  });

  // Consume SSE stream and track results
  const results = new Map<string, string>();
  const reader = runResponse.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const lines = buffer.split('\\\\n\\\\n');
    buffer = lines.pop() ?? '';

    for (const line of lines) {
      if (!line.startsWith('data: ')) continue;
      const event = JSON.parse(line.slice(6));

      if (event.type === 'component') {
        results.set(event.name, event.status);
        console.log(\\\`  \\\${event.name}: \\\${event.status}\\\\\`);
      }
    }
  }

  // Step 3: Verify by listing again
  const verifyResponse = await fetch('/api/pipeline/compositions/list');
  const verified = await verifyResponse.json();

  let allDone = true;
  for (const section of verified.sections) {
    for (const comp of [...section.components, ...section.wrappers]) {
      if (comp.status !== 'exists') {
        allDone = false;
        console.log(\\\`  Still not ready: \\\${comp.name} (\\\${comp.status})\\\\\`);
      }
    }
  }

  if (allDone) {
    console.log('All compositions generated successfully!');
  } else {
    console.log('Some compositions still need attention.');
  }
  `);

  console.log("");
}

// ============================================================================
// Example 5: Understanding the SSE stream format
// ============================================================================

/**
 * The createSseStream() helper creates a TransformStream-based SSE writer.
 *
 * SSE format:
 *   Each event is a line starting with "data: " followed by a JSON object,
 *   terminated by two newlines (\n\n).
 *
 * The stream emits these event types in order:
 *
 * For each component in the `components` array:
 *   1. { type: 'component', name: '<name>', status: 'generating' }
 *   2. { type: 'log', message: '[compositions] Generating component: <name>', jobId: '<id>' }
 *   3. (Multiple log events from Claude Code stderr)
 *   4. { type: 'component', name: '<name>', status: 'done' }  — or 'error'
 *   5. { type: 'progress', percent: <N>, jobId: '<id>' }
 *
 * For wrappers (all at once via python script):
 *   1. { type: 'component', name: '<name>', status: 'generating' } — for each wrapper
 *   2. (Log events from python script stdout/stderr)
 *   3. { type: 'component', name: '<name>', status: 'done' | 'error' } — for each wrapper
 *   4. { type: 'progress', percent: <N>, jobId: '<id>' }
 *
 * Finally:
 *   - { type: 'job', jobId: '<id>' }
 *   - { type: 'complete', jobId: '<id>' }
 *
 * On error:
 *   - { type: 'error', message: '<error message>' }
 *   - Stream closes
 */

function example5_sseFormat(): void {
  console.log("=== Example 5: SSE Stream Format ===\n");

  // Example raw SSE stream for generating 2 components and 1 wrapper:
  const rawSseStream = `\
data: {"type":"component","name":"IntroTitle","status":"generating"}

data: {"type":"log","message":"[compositions] Generating component: IntroTitle","jobId":"job-001"}

data: {"type":"log","message":"Reading spec file...","jobId":"job-001"}

data: {"type":"log","message":"Generating TypeScript/React code...","jobId":"job-001"}

data: {"type":"component","name":"IntroTitle","status":"done"}

data: {"type":"progress","percent":33,"jobId":"job-001"}

data: {"type":"component","name":"LogoReveal","status":"generating"}

data: {"type":"log","message":"[compositions] Generating component: LogoReveal","jobId":"job-001"}

data: {"type":"component","name":"LogoReveal","status":"done"}

data: {"type":"progress","percent":67,"jobId":"job-001"}

data: {"type":"component","name":"introWrapper","status":"generating"}

data: {"type":"log","message":"Running generate_section_compositions.py...","jobId":"job-001"}

data: {"type":"component","name":"introWrapper","status":"done"}

data: {"type":"progress","percent":100,"jobId":"job-001"}

data: {"type":"job","jobId":"job-001"}

data: {"type":"complete","jobId":"job-001"}

`;

  console.log("Raw SSE stream example:");
  console.log(rawSseStream);
}

// ============================================================================
// Example 6: Understanding internal helpers
// ============================================================================

/**
 * Internal helper functions used by the route handlers:
 *
 * findSpecForComponent(componentName: string): string
 *   Walks the `specs/` directory tree recursively looking for a file whose
 *   basename (without extension) matches the component name.
 *   Returns the file content as a string, or "" if not found.
 *
 *   Example: findSpecForComponent("IntroTitle")
 *     → Searches specs/ for any file named "IntroTitle.*"
 *     → If found at specs/intro/IntroTitle.md, returns its content
 *
 * buildComponentPrompt(name: string, spec: string): string
 *   Constructs the prompt sent to Claude Code for generating a component.
 *   Includes the component name, target output path, and the spec content.
 *
 * listSpecComponents(specDir: string): string[]
 *   Walks a spec directory and returns all unique basenames (without extension).
 *   Used by the list endpoint to discover which components should exist.
 *
 * getLastErrorForComponent(name: string): string | undefined
 *   Queries the SQLite jobs database for the most recent 'compositions' stage
 *   job with status='error' whose params include the given component name.
 *   Returns the error message, or undefined if no error found.
 *
 * buildEntry(name: string): CompositionEntry
 *   Checks if remotion/src/remotion/<name>.tsx exists and queries for last error.
 *   Returns { name, status: 'exists' | 'missing' | 'error', lastError? }.
 *
 * loadManifestFiles(): string[]
 *   Reads the staging manifest from outputs/veo/ (tries staging.json,
 *   staging-manifest.json, manifest.json in order). Returns array of filenames.
 */

function example6_internalHelpers(): void {
  console.log("=== Example 6: Internal Helper Functions ===\n");

  // Demonstrate the spec directory structure that drives component discovery
  const exampleSpecTree = `
  specs/
  ├── intro/
  │   ├── IntroTitle.md          → component "IntroTitle"
  │   ├── BackgroundGradient.md  → component "BackgroundGradient"
  │   └── LogoReveal.md          → component "LogoReveal"
  ├── main/
  │   ├── ProductShowcase.md     → component "ProductShowcase"
  │   └── FeatureHighlight.md    → component "FeatureHighlight"
  └── outro/
      ├── CreditsRoll.md         → component "CreditsRoll"
      └── CallToAction.md        → component "CallToAction"
  `;

  console.log("Expected spec directory structure:");
  console.log(exampleSpecTree);

  // Demonstrate the Remotion output directory structure
  const exampleRemotionTree = `
  remotion/src/remotion/
  ├── IntroTitle.tsx              ← generated by Claude Code
  ├── BackgroundGradient.tsx      ← generated by Claude Code
  ├── introWrapper.tsx            ← generated by python script
  ├── IntroCompositionWrapper.tsx  ← generated by python script
  └── ...
  `;

  console.log("Generated Remotion component structure:");
  console.log(exampleRemotionTree);

  // Demonstrate the Claude prompt that gets generated
  const examplePrompt = `
You are Claude Code. Generate a Remotion component.

Component name: IntroTitle
Target directory: remotion/src/remotion/
Output file: remotion/src/remotion/IntroTitle.tsx

Use the spec below to implement the component accurately.

--- SPEC ---
# IntroTitle Component

Display the video title with a fade-in animation over the first 2 seconds.

## Props
- title: string — The title text to display
- subtitle?: string — Optional subtitle

## Animation
- Fade in from opacity 0 to 1 over frames 0-60
- Scale from 0.8 to 1.0 with spring animation
- Use Remotion's useCurrentFrame() and interpolate()

## Styling
- Centered on screen
- Font: Inter, 64px, bold, white
- Text shadow for readability
--- END SPEC ---

Return valid TypeScript/React code.
`;

  console.log("Example Claude prompt for component generation:");
  console.log(examplePrompt);
}

// ============================================================================
// Example 7: Executor registration pattern
// ============================================================================

/**
 * The compositions executor is registered via registerExecutor() at module
 * load time. This is the pattern used across all pipeline stages.
 *
 * registerExecutor("compositions", (params, send) => {
 *   // Factory function: receives job params and SSE send callback
 *   return async (onLog) => {
 *     // Executor function: receives onLog for logging
 *     // onLog(msg) — appends to job logs in DB + emits SSE log event
 *     // (onLog as any).progress?.(percent) — updates progress in DB + emits SSE
 *
 *     // params.components — string[] of component names
 *     // params.wrappers — string[] of wrapper names
 *     // send({ type, ... }) — emits custom SSE events (component status, etc.)
 *   };
 * });
 *
 * The executor is invoked by runPipelineStage("compositions", body, send),
 * which also handles DAG-based prerequisite resolution. For "compositions",
 * the prerequisites are "audio-sync" and "veo" (per PIPELINE_DAG).
 */

function example7_executorPattern(): void {
  console.log("=== Example 7: Executor Registration Pattern ===\n");

  console.log(`
  // In the route file, the executor is registered at module load time:
  registerExecutor("compositions", (params, send) => {
    return async (onLog) => {
      const components = (params.components as string[]) ?? [];
      const wrappers = (params.wrappers as string[]) ?? [];
      const progressFn = (onLog as any).progress;

      const total = components.length + wrappers.length || 1;
      let completed = 0;

      // Phase 1: Generate components via Claude Code (sequential)
      for (const name of components) {
        send({ type: "component", name, status: "generating" });
        const spec = findSpecForComponent(name);
        const prompt = buildComponentPrompt(name, spec);
        await runClaudeFix(prompt, REMOTION_SCOPE_DIR, (line) => onLog(line));
        send({ type: "component", name, status: "done" });
        completed++;
        progressFn?.(Math.round((completed / total) * 100));
      }

      // Phase 2: Generate wrappers via python script (batch)
      if (wrappers.length > 0) {
        await spawnPythonScript("generate_section_compositions.py");
        // Check which wrapper files were created
        for (const name of wrappers) {
          const exists = fs.existsSync(\\\`remotion/src/remotion/\\\${name}.tsx\\\\\`);
          send({ type: "component", name, status: exists ? "done" : "error" });
        }
      }
    };
  });

  // The POST handler then calls:
  const jobId = await runPipelineStage("compositions", body, send);
  // This resolves DAG prerequisites (audio-sync, veo) before running compositions.
  `);

  console.log("");
}

// ============================================================================
// Example 8: Error handling and retry patterns
// ============================================================================

/**
 * When a component generation fails:
 *   1. The executor emits { type: 'component', name, status: 'error' }
 *   2. The error is thrown, causing the job to be marked as 'error' in the DB
 *   3. The SSE stream emits { type: 'error', message: '...' } and closes
 *   4. The error message is stored in the job's `error` column
 *
 * On subsequent GET /api/pipeline/compositions/list calls:
 *   - getLastErrorForComponent() queries the DB for the most recent error
 *   - The component's status is set to 'error' with lastError populated
 *
 * To retry:
 *   - Call POST /api/pipeline/compositions/run again with the failed components
 *   - Or use the job retry endpoint: POST /api/jobs/<jobId>/retry
 */

function example8_errorHandling(): void {
  console.log("=== Example 8: Error Handling & Retry ===\n");

  console.log(`
  // After a failed generation, the list endpoint shows:
  {
    "sections": [{
      "sectionId": "intro",
      "components": [
        { "name": "IntroTitle", "status": "exists" },
        {
          "name": "ParticleEffect",
          "status": "error",
          "lastError": "Claude CLI timeout after 300s"
        }
      ],
      "wrappers": [...]
    }]
  }

  // Retry just the failed component:
  await fetch('/api/pipeline/compositions/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      components: ['ParticleEffect'],
      wrappers: [],
    }),
  });

  // Or retry the entire job via the jobs API:
  await fetch(\\\`api/jobs/\\\${failedJobId}/retry\\\\\`, { method: 'POST' });
  `);

  console.log("");
}

// ============================================================================
// Example 9: Asset staging manifest formats
// ============================================================================

/**
 * The asset staging endpoint supports multiple manifest formats.
 * It checks these files in order:
 *   1. outputs/veo/staging.json
 *   2. outputs/veo/staging-manifest.json
 *   3. outputs/veo/manifest.json
 *
 * Each can be either:
 *   - A JSON array of filenames: ["intro/bg.mp4", "main/demo.mp4"]
 *   - A JSON object with a `files` array: { "files": ["intro/bg.mp4"], ... }
 */

function example9_manifestFormats(): void {
  console.log("=== Example 9: Asset Staging Manifest Formats ===\n");

  // Format 1: Simple array
  const format1 = ["intro/background.mp4", "intro/logo.mp4", "main/demo.mp4"];
  console.log("Format 1 (array):", JSON.stringify(format1, null, 2));

  // Format 2: Object with files property
  const format2 = {
    files: ["intro/background.mp4", "intro/logo.mp4"],
    generatedAt: "2025-01-15T10:00:00Z",
    veoModel: "veo-2.0-generate-001",
  };
  console.log("Format 2 (object):", JSON.stringify(format2, null, 2));

  // File copy behavior
  console.log(`
  Copy behavior:
    Source:      outputs/veo/intro/background.mp4
    Destination: remotion/public/intro/background.mp4

    - Creates remotion/public/intro/ directory if it doesn't exist
    - Skips if source file doesn't exist (no error)
    - Skips if destination file already exists (no overwrite)
  `);
}

// ============================================================================
// Example 10: React hook pattern for consuming the SSE stream
// ============================================================================

/**
 * Demonstrates a React hook pattern for consuming the compositions SSE stream
 * in a Next.js client component.
 */

function example10_reactHookPattern(): void {
  console.log("=== Example 10: React Hook Pattern ===\n");

  console.log(`
  // hooks/useCompositionGeneration.ts
  'use client';

  import { useState, useCallback } from 'react';

  type ComponentStatus = {
    name: string;
    status: 'pending' | 'generating' | 'done' | 'error';
  };

  export function useCompositionGeneration() {
    const [components, setComponents] = useState<ComponentStatus[]>([]);
    const [progress, setProgress] = useState(0);
    const [jobId, setJobId] = useState<string | null>(null);
    const [isRunning, setIsRunning] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const generate = useCallback(async (
      componentNames: string[],
      wrapperNames: string[]
    ) => {
      setIsRunning(true);
      setError(null);
      setProgress(0);

      // Initialize component statuses
      setComponents([
        ...componentNames.map(name => ({ name, status: 'pending' as const })),
        ...wrapperNames.map(name => ({ name, status: 'pending' as const })),
      ]);

      const response = await fetch('/api/pipeline/compositions/run', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          components: componentNames,
          wrappers: wrapperNames,
        }),
      });

      const reader = response.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split('\\\\n\\\\n');
          buffer = lines.pop() ?? '';

          for (const line of lines) {
            if (!line.startsWith('data: ')) continue;
            const event = JSON.parse(line.slice(6));

            switch (event.type) {
              case 'component':
                setComponents(prev =>
                  prev.map(c =>
                    c.name === event.name
                      ? { ...c, status: event.status }
                      : c
                  )
                );
                break;
              case 'progress':
                setProgress(event.percent);
                break;
              case 'job':
                setJobId(event.jobId);
                break;
              case 'error':
                setError(event.message);
                break;
            }
          }
        }
      } finally {
        setIsRunning(false);
      }
    }, []);

    return { components, progress, jobId, isRunning, error, generate };
  }

  // Usage in a component:
  // const { components, progress, isRunning, generate } = useCompositionGeneration();
  // <button onClick={() => generate(['IntroTitle'], ['introWrapper'])}>Generate</button>
  // <ProgressBar value={progress} />
  // {components.map(c => <ComponentStatus key={c.name} {...c} />)}
  `);
}

// ============================================================================
// Run all examples
// ============================================================================

async function main(): Promise<void> {
  await example1_compositionsRun();
  await example2_assetStaging();
  await example3_compositionsList();
  await example4_fullWorkflow();
  example5_sseFormat();
  example6_internalHelpers();
  example7_executorPattern();
  example8_errorHandling();
  example9_manifestFormats();
  example10_reactHookPattern();

  console.log("=== All examples completed successfully ===");
}

main().catch(console.error);