#!/usr/bin/env python3
"""
Example: How to use the sync_audio_pipeline module.

This script demonstrates both:
  1. Running the pipeline as a CLI subprocess (the primary intended usage).
  2. Importing and calling individual functions programmatically.

Prerequisites:
  - ffmpeg installed (or pydub as fallback)
  - faster-whisper installed (`pip install faster-whisper`)
  - Segment WAV files already generated by a TTS step

Directory structure expected (relative to project root):
  project_root/
  ├── project.json                  # Contains sectionGroups mapping
  ├── outputs/
  │   └── tts/
  │       ├── seg_001.wav           # Individual TTS segment WAVs
  │       ├── seg_002.wav
  │       └── seg_003.wav
  ├── remotion/
  │   └── public/                   # Remotion public assets directory
  └── scripts/
      └── sync_audio_pipeline.py    # The module being demonstrated
"""

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List, Dict, Any

# ---------------------------------------------------------------------------
# Helper: set up sys.path so we can import from the scripts/ directory
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# Adjust this relative path based on where this example lives vs. the module
SCRIPTS_DIR = os.path.join(SCRIPT_DIR, "..", "scripts")
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

try:
    # Now import functions from the module
    from sync_audio_pipeline import (
        load_project,
        get_segment_wav_path,
        get_wav_duration,
        concatenate_wavs_ffmpeg,
        copy_to_remotion,
        generate_word_timestamps,
        process_section,
    )
except ImportError:
    # Fallback for when the module isn't actually in the expected path during extraction
    pass


# ===================================================================
# EXAMPLE 1: Run as a subprocess (primary / production usage)
# ===================================================================
def example_subprocess_usage() -> None:
    """
    The module is designed to be invoked as a standalone CLI script by a
    Next.js API route. The API route spawns the process and reads JSON
    progress lines from stdout.
    """
    print("=" * 60)
    print("EXAMPLE 1: Subprocess invocation (production pattern)")
    print("=" * 60)

    script_path = os.path.join(SCRIPTS_DIR, "sync_audio_pipeline.py")

    cmd = [
        sys.executable,
        script_path,
        "--project-dir", "/path/to/project",
        "--output-dir", "/path/to/project/outputs/tts/",
        "--remotion-public", "/path/to/project/remotion/public/",
    ]

    print(f"\nCommand that would be run:\n  {' '.join(cmd)}\n")
    print("Each stdout line is a JSON progress object.")
    print("The caller parses each line to track per-section progress.\n")


# ===================================================================
# EXAMPLE 2: Programmatic usage of individual functions
# ===================================================================
def example_programmatic_usage() -> None:
    """
    Demonstrates importing and calling individual pipeline functions
    directly from Python, useful for testing or custom orchestration.
    """
    print("=" * 60)
    print("EXAMPLE 2: Programmatic function usage")
    print("=" * 60)

    # --- Create a temporary project structure for demonstration ---
    with tempfile.TemporaryDirectory() as tmpdir:
        project_dir = tmpdir
        output_dir = os.path.join(tmpdir, "outputs", "tts")
        remotion_public = os.path.join(tmpdir, "remotion", "public")
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(remotion_public, exist_ok=True)

        # 2a. Create a minimal project.json
        project_data = {
            "title": "Demo Project",
            "sectionGroups": {
                "intro": ["seg_001", "seg_002"],
                "chapter1": ["seg_003"],
            },
        }
        project_json_path = os.path.join(project_dir, "project.json")
        with open(project_json_path, "w") as f:
            json.dump(project_data, f, indent=2)

        # 2b. load_project()
        try:
            project = load_project(project_dir)
            print(f"\n✓ Loaded project with sections: {list(project['sectionGroups'].keys())}")
        except NameError:
            print("\n☐ load_project not available (import failed)")
            return

        # 2c. get_segment_wav_path()
        seg_path = get_segment_wav_path(output_dir, "seg_001")
        print(f"✓ Segment WAV path: {seg_path}")

        # 2d. Create dummy WAV files for demonstration
        _create_dummy_wav(os.path.join(output_dir, "seg_001.wav"), duration_ms=1500)
        _create_dummy_wav(os.path.join(output_dir, "seg_002.wav"), duration_ms=2000)
        _create_dummy_wav(os.path.join(output_dir, "seg_003.wav"), duration_ms=1000)
        print("✓ Created dummy segment WAV files")

        # 2e. get_wav_duration()
        duration = get_wav_duration(Path(os.path.join(output_dir, "seg_001.wav")))
        print(f"✓ seg_001.wav duration: {duration:.3f}s")

        # 2f. concatenate_wavs_ffmpeg()
        section_dir = os.path.join(output_dir, "intro")
        os.makedirs(section_dir, exist_ok=True)
        concat_path = Path(os.path.join(section_dir, "concatenated.wav"))

        segment_paths = [
            Path(os.path.join(output_dir, "seg_001.wav")),
            Path(os.path.join(output_dir, "seg_002.wav")),
        ]
        concatenate_wavs_ffmpeg(segment_paths, concat_path)
        concat_duration = get_wav_duration(concat_path)
        print(f"✓ Concatenated intro WAV duration: {concat_duration:.3f}s")

        # 2g. copy_to_remotion()
        dest = copy_to_remotion(concat_path, remotion_public, "intro")
        print(f"✓ Copied to Remotion: {dest}")

        # 2h. process_section()
        print("\n--- process_section() demo ---")
        try:
            result = process_section(
                section_id="chapter1",
                segment_ids=["seg_003"],
                output_dir=output_dir,
                remotion_public=remotion_public,
            )
            print(f"✓ process_section result: {json.dumps(result, indent=2)}")
        except (ImportError, Exception) as e:
            print(f"☐ process_section demo skipped or failed: {e}")

        # 2i. Handling missing segments gracefully
        print("\n--- Missing segment handling ---")
        result = process_section(
            section_id="nonexistent_section",
            segment_ids=["missing_seg_999"],
            output_dir=output_dir,
            remotion_public=remotion_public,
        )
        print(f"✓ Missing segment result: {json.dumps(result, indent=2)}")

    print("\n✓ All examples completed.")


def _create_dummy_wav(path: str, duration_ms: int = 1000) -> None:
    """Create a silent WAV file for demonstration purposes."""
    try:
        subprocess.run(
            [
                "ffmpeg", "-y",
                "-f", "lavfi",
                "-i", "anullsrc=r=16000:cl=mono",
                "-t", str(duration_ms / 1000.0),
                "-c:a", "pcm_s16le",
                path,
            ],
            capture_output=True,
            check=True,
        )
        return
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    try:
        from pydub import AudioSegment
        silent = AudioSegment.silent(duration=duration_ms, frame_rate=16000)
        silent.export(path, format="wav")
        return
    except ImportError:
        pass

    import struct
    sample_rate = 16000
    num_samples = int(sample_rate * duration_ms / 1000)
    data_size = num_samples * 2
    with open(path, "wb") as f:
        f.write(b"RIFF")
        f.write(struct.pack("<I", 36 + data_size))
        f.write(b"WAVE")
        f.write(b"fmt ")
        f.write(struct.pack("<I", 16))
        f.write(struct.pack("<H", 1))
        f.write(struct.pack("<H", 1))
        f.write(struct.pack("<I", sample_rate))
        f.write(struct.pack("<I", sample_rate * 2))
        f.write(struct.pack("<H", 2))
        f.write(struct.pack("<H", 16))
        f.write(b"data")
        f.write(struct.pack("<I", data_size))
        f.write(b"\x00" * data_size)


if __name__ == "__main__":
    example_subprocess_usage()
    print()
    example_programmatic_usage()