# pdd/agentic_langtest.py
from __future__ import annotations
import csv
import shlex
import shutil
import sys
from pathlib import Path

from pdd.get_run_command import shell_safe_substitute


def _which(cmd: str) -> bool:
    """Checks if a command-line tool exists in the system's PATH.

    Args:
        cmd: The name of the command to check (e.g., "npm", "mvn").

    Returns:
        True if the command is found, False otherwise.
    """
    return shutil.which(cmd) is not None


def _find_project_root(start_path: str) -> Path:
    """Finds the project root by searching upwards for common project files.

    Starting from `start_path`, it traverses up the directory tree looking for
    marker files like `build.gradle`, `pom.xml`, or `package.json`.

    Args:
        start_path: The file or directory path to start the search from.

    Returns:
        The resolved Path to the project root directory. If no marker is found,
        it returns the parent of the starting path's resolved directory.
    """
    p = Path(start_path).resolve()
    while p != p.parent:
        if any((p / f).exists() for f in [
            "build.gradle",
            "build.gradle.kts",
            "pom.xml",
            "package.json",
            "jest.config.js",
        ]):
            return p
        p = p.parent
    return Path(start_path).resolve().parent


def _run_test_command_for_language(lang: str) -> str:
    """Return the `run_test_command` for `lang` from `language_format.csv`, or ''.

    Keyed by the lowercase language *name* (e.g. "python", "javascript"). Returns
    an empty string when the CSV is missing or the language has no command."""
    csv_path = Path(__file__).parent.parent / "pdd" / "data" / "language_format.csv"
    if not csv_path.exists():
        return ""
    with open(csv_path, newline="") as handle:
        for row in csv.DictReader(handle):
            if (row.get("language") or "").strip().lower() == lang:
                return (row.get("run_test_command") or "").strip()
    return ""


def default_verify_cmd_for(lang: str, unit_test_file: str) -> str | None:
    """Return a default shell command to run tests for `lang` and `unit_test_file`.

    Resolution order:
    1. `language_format.csv`'s `run_test_command` for the language, substituting the
       (shell-quoted) test path for its `{file}` placeholder.
    2. Otherwise, for **Python**, a pytest command (interpreter and path both
       shell-quoted).
    3. Otherwise `None`, so agentic mode handles test discovery/execution.

    The command is executed by callers with `bash -lc` / `shell=True`, so the test
    path MUST be shell-quoted (`shlex.quote`) AND the `{file}` placeholder MUST be a
    standalone bare word: `shlex.quote` wraps its value in single quotes, which only
    neutralize metacharacters at a bare word — a CSV template that quotes the
    placeholder (`mocha "{file}"`) would leave the single quotes literal and still
    execute a `$(...)` in the path. `shell_safe_substitute` enforces this and returns
    None for an unsafe template (fall through to the Python fallback / agentic mode).
    """
    lang = lang.lower()

    # 1. CSV lookup by language name.
    csv_cmd = _run_test_command_for_language(lang)
    if csv_cmd:
        substituted = shell_safe_substitute(csv_cmd, {"{file}": unit_test_file})
        if substituted is not None:
            return substituted

    # 2. Hardcoded Python fallback.
    if lang == "python":
        return f"{shlex.quote(sys.executable)} -m pytest {shlex.quote(unit_test_file)} -q"

    # 3. No known command — agentic mode handles it.
    return None


def missing_tool_hints(lang: str, verify_cmd: str | None, project_root: Path) -> str | None:
    """Checks for missing toolchains and returns helpful installation hints.

    This function inspects the environment and the generated verification command
    to identify missing dependencies (like npm, javac, etc.) and provides
    user-friendly, colored installation instructions for common platforms.

    Args:
        lang: The programming language.
        verify_cmd: The verification command generated by `default_verify_cmd_for`.
        project_root: The root directory of the project being tested.

    Returns:
        A formatted string with installation hints if tools are missing,
        otherwise None.
    """
    if not verify_cmd:
        return None

    need = []
    if lang in ("typescript", "javascript"):
        if not _which("npm"):
            need.append("npm (Node.js)")
    if lang == "java":
        if not _which("javac") or not _which("java"):
            need.append("Java JDK (javac, java)")
        jar_present = any(
            p.name.endswith(".jar") and "junit" in p.name.lower() and "console" in p.name.lower()
            for p in project_root.glob("*.jar")
        )
        if not jar_present:
            need.append("JUnit ConsoleLauncher jar (e.g. junit-platform-console-standalone.jar)")
    if lang == "cpp":
        if not _which("g++"):
            need.append("g++")

    if not need:
        return None

    install_lines = []
    if "npm (Node.js)" in need:
        install_lines += [
            "macOS:  brew install node",
            "Ubuntu: sudo apt-get update && sudo apt-get install -y nodejs npm",
        ]
    if "Java JDK (javac, java)" in need:
        install_lines += [
            "macOS:  brew install openjdk",
            "Ubuntu: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk",
        ]
    if "JUnit ConsoleLauncher jar (e.g. junit-platform-console-standalone.jar)" in need:
        install_lines += [
            "Download the ConsoleLauncher jar from Maven Central and place it in your project root, e.g:",
            "  curl -LO https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar",
        ]
    if "g++" in need:
        install_lines += [
            "macOS:  xcode-select --install   # or: brew install gcc",
            "Ubuntu: sudo apt-get update && sudo apt-get install -y build-essential",
        ]

    return (
        "[yellow]Some tools required to run non-Python tests seem missing.[/yellow]\n  - "
        + "\n  - ".join(need)
        + "\n[dim]Suggested installs:\n  "
        + "\n  ".join(install_lines)
        + "[/dim]"
    )


# example.py
import tempfile
from pathlib import Path
from rich import print as rprint
from rich.panel import Panel

# Assume the module above is in pdd/agentic_langtest.py
# and your current directory is the parent of 'pdd'.
from pdd.agentic_langtest import default_verify_cmd_for, missing_tool_hints


def demonstrate_js_project(root: Path):
    """
    Sets up a mock JS project and demonstrates the module's functions.
    """
    rprint(Panel("[bold cyan]Demonstrating with a JavaScript Project[/bold cyan]"))

    # 1. Create a mock project structure with a package.json file.
    # The `_find_project_root` helper will use this file as a marker.
    (root / "package.json").write_text(
        """{
          "name": "my-project",
          "scripts": { "test": "echo 'JS tests would run here' && exit 0" }
        }""",
        encoding="utf-8",
    )
    test_file = root / "src" / "app.test.js"
    test_file.parent.mkdir()
    test_file.touch()
    print(f"Created a temporary JS project at: {root}")
    print(f"Test file is at: {test_file}\n")

    # 2. Generate the default verification command for JavaScript.
    # The function will find the project root and generate an `npm` command.
    lang = "javascript"
    verify_cmd = default_verify_cmd_for(lang, str(test_file))

    rprint(Panel(
        f"[bold]Generated Command:[/bold]\n{verify_cmd}",
        title="[green]default_verify_cmd_for Result[/green]",
        border_style="green",
    ))

    # 3. Check for missing tools (like npm) and get installation hints.
    # The output will depend on whether 'npm' is installed on your system.
    hints = missing_tool_hints(lang, verify_cmd, root)

    if hints:
        rprint(Panel(
            hints,
            title="[yellow]missing_tool_hints Result[/yellow]",
            border_style="yellow",
        ))
    else:
        rprint(Panel(
            "No missing tools detected. 'npm' is likely installed.",
            title="[green]missing_tool_hints Result[/green]",
            border_style="green",
        ))


def demonstrate_python_project(root: Path):
    """
    Shows a simpler case for a Python test file.
    """
    rprint(Panel("\n[bold cyan]Demonstrating with a Python Project[/bold cyan]"))
    test_file = root / "test_simple.py"
    test_file.touch()
    print(f"Created a temporary Python test file at: {test_file}\n")

    # Generate the command for Python.
    lang = "python"
    verify_cmd = default_verify_cmd_for(lang, str(test_file))
    rprint(Panel(
        f"[bold]Generated Command:[/bold]\n{verify_cmd}",
        title="[green]default_verify_cmd_for Result[/green]",
        border_style="green",
    ))


def main():
    """
    Main function to run the demonstrations in a temporary directory.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        project_root = Path(tmpdir)
        demonstrate_js_project(project_root)
        demonstrate_python_project(project_root)


if __name__ == "__main__":
    main()
