from __future__ import annotations

import sys
from pathlib import Path

# Ensure the parent directory is in the path so we can import the pdd package
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pdd.checkup_interactive_session import (
    ApprovedPatch,
    FakeInteractiveSession,
    PiInteractiveSession,
)


def main() -> None:
    try:
        from rich.console import Console
    except ImportError:
        raise SystemExit("Install 'rich' to run this example: pip install rich")

    console = Console()
    console.print("[bold blue]Interactive Prompt-Repair Session Example[/bold blue]\n")

    # 1. Check if the Pi-backed session agent is available on this system
    pi_available = PiInteractiveSession.is_available()
    console.print(f"Pi backend available: [bold]{pi_available}[/bold]")

    # 2. Prepare some simulated ApprovedPatches
    # In a real Pi session, these are generated by the agent and selected by the user.
    sample_patch = ApprovedPatch(
        kind="regex_replace",
        target=Path("prompts/classifier.txt"),
        anchor={"pattern": "classify as safe"},
        replacement="classify strictly as safe or unsafe",
    )

    # 3. Create and seed an interactive session using the Fake backend for deterministic execution
    console.print("\n[yellow]Initializing FakeInteractiveSession for testing...[/yellow]")
    session = FakeInteractiveSession(patches=[sample_patch])

    # Seed the session with a prompt source set report (can be any dict/report structure)
    mock_report = {
        "sources": ["prompts/classifier.txt"],
        "issues": [{"type": "ambiguity", "line": 12}],
    }
    session.seed(mock_report)
    console.print("Session seeded successfully.")

    # Run the session (the fake session runs instantly and marks itself as completed)
    session.run()
    console.print(f"Session ran: [green]{session.ran}[/green]")

    # 4. Retrieve and inspect approved patches
    approved = session.approved_patches()
    console.print(f"\nRetrieved [bold green]{len(approved)}[/bold green] approved patch(es):")
    for idx, patch in enumerate(approved, 1):
        console.print(f"  [bold]Patch #{idx}[/bold]:")
        console.print(f"    Kind: {patch.kind}")
        console.print(f"    Target: {patch.target}")
        console.print(f"    Anchor: {patch.anchor}")
        console.print(f"    Replacement: [italic]{patch.replacement}[/italic]")


if __name__ == "__main__":
    main()
