import requests

def call_cloud_function(firebase_token):
    # Replace with your Cloud Function URL
    CLOUD_FUNCTION_URL = "https://us-central1-prompt-driven-development.cloudfunctions.net/on_request_example"
    
    # Make a request to your Cloud Function with the Firebase token in the Authorization header
    headers = {"Authorization": f"Bearer {firebase_token}"}
    response = requests.get(CLOUD_FUNCTION_URL, headers=headers)
    
    return response.json()

firebase_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjZjYzNmY2I2NDAzMjc2MGVlYjljMjZmNzdkNDA3YTY5NGM1MmIwZTMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiR3JlZyBUYW5ha2EiLCJwaWN0dXJlIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzI0NjMyNzE2P3Y9NCIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9wcm9tcHQtZHJpdmVuLWRldmVsb3BtZW50IiwiYXVkIjoicHJvbXB0LWRyaXZlbi1kZXZlbG9wbWVudCIsImF1dGhfdGltZSI6MTcyNzY2MDYyMiwidXNlcl9pZCI6IlF4aGRFeWNpSzdhcms3THhNZHZybTM4VWZzbjEiLCJzdWIiOiJReGhkRXljaUs3YXJrN0x4TWR2cm0zOFVmc24xIiwiaWF0IjoxNzI3NjYwNjIyLCJleHAiOjE3Mjc2NjQyMjIsImVtYWlsIjoiZ2x0QGFsdW1uaS5jYWx0ZWNoLmVkdSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnaXRodWIuY29tIjpbIjI0NjMyNzE2Il0sImVtYWlsIjpbImdsdEBhbHVtbmkuY2FsdGVjaC5lZHUiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnaXRodWIuY29tIn19.DcD_R9RtpetFHezDFWfmru6B8-e3qIk70SPghiES2O2CMFcaVUhn20QpSDbaaKORlqSn7Z8RAzokUrLg8XmgJqnOfv18gH_993agMN5ityxYRgaF19wrQKQjbYWfOuQZSiBQ3mrOMd_nEuedjqXlg7RBl4HHgc67SZeZoBIO4QY9EjZlTW2hsb0UyPw6j3ev1w44qRiOdV0vT4fEC-Xav3jdGiqsqIXSBL_-pDeta0BK1RNnIvEg6lEasbe9GOqmAiKmm4Icci_6SfIu28vZoQ-r7mwvR9TqDHq5nhj2h25GiOVIrggoGpYdltLL9V6NPWgZ1ZTCY0zkErRvZ_O2DQ"

# Call the Cloud Function
result = call_cloud_function(firebase_token)
print(f"Cloud Function Result: {result}")
