# Install with pip install firecrawl-py
from firecrawl import FirecrawlApp
import os

app = FirecrawlApp(api_key=os.environ.get('FIRECRAWL_API_KEY', 'YOUR_API_KEY'))

response = app.scrape_url(url='google.com/', params={
	'formats': [ 'markdown' ],
})

print(response)
# {'markdown': "[About](https://about.google/?fg=1&utm_source=google-US&utm_medium=referral&utm_campaign=hp-header) [Store](https://store.google.com/US?utm_source=hp_header&utm_medium=google_ooo&utm_campaign=GS100042&hl=en-US)\n\n[Gmail](https://mail.google.com/mail/&ogbl)\n\n[Images](https://www.google.com/imghp?hl=en&ogbl)\n\n[Google apps](https://www.google.com/intl/en/about/products)\n\n[Sign in](https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAmgQ)\n\n[iframe](https://ogs.google.com/widget/callout?prid=19046229&pgid=19046228&puid=2e6b2513ec221596&eom=1&cce=1&dc=1&origin=https%3A%2F%2Fwww.google.com&cn=callout&pid=1&spid=538&hl=en)\n\n![Google](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png)\n\nChoose what you’re giving feedback on\n\n* * *\n\nSee more\n\nDelete\n\nDelete\n\nReport inappropriate predictions\n\nI'm Feeling Curious\n\nI'm Feeling Hungry\n\nI'm Feeling Adventurous\n\nI'm Feeling Playful\n\nI'm Feeling Stellar\n\nI'm Feeling Doodley\n\nI'm Feeling Trendy\n\nI'm Feeling Artistic\n\nI'm Feeling Funny\n\n[Advertising](https://www.google.com/intl/en_us/ads/?subid=ww-ww-et-g-awa-a-g_hpafoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpafooter&fg=1) [Business](https://www.google.com/services/?subid=ww-ww-et-g-awa-a-g_hpbfoot1_1!o2&utm_source=google.com&utm_medium=referral&utm_campaign=google_hpbfooter&fg=1) [How Search works](https://google.com/search/howsearchworks/?fg=1)\n\n[![](<Base64-Image-Removed>)Our third decade of climate action: join us](https://sustainability.google/?utm_source=googlehpfooter&utm_medium=housepromos&utm_campaign=bottom-footer&utm_content=)\n\n[Privacy](https://policies.google.com/privacy?hl=en&fg=1) [Terms](https://policies.google.com/terms?hl=en&fg=1)\n\nSettings\n\n[Search settings](https://www.google.com/preferences?hl=en&fg=1)\n\n[Advanced search](https://www.google.com/advanced_search?hl=en&fg=1)\n\n[Your data in Search](https://www.google.com/history/privacyadvisor/search/unauth?utm_source=googlemenu&fg=1&cctld=com)\n\n[Search history](https://www.google.com/history/optout?hl=en&fg=1)\n\n[Search help](https://support.google.com/websearch/?p=ws_results_help&hl=en&fg=1)\n\nSend feedback\n\nDark theme: Off\n\nGoogle apps", 'metadata': {'referrer': 'origin', 'title': 'Google', 'language': 'en', 'scrapeId': 'f5433150-c76b-4d20-9329-7a9c20cbb2fd', 'sourceURL': 'http://google.com/', 'url': 'https://www.google.com/', 'statusCode': 200}}