# Here's a concise example of how to use the `fix_errors_from_unit_tests` function from the `fix_errors_from_unit_tests.py` module. This example includes documentation for the input and output parameters.

# ### Example Usage

# ```python
# Filename: example_usage.py

import os
from fix_errors_from_unit_tests import fix_errors_from_unit_tests

# Set the PDD_PATH environment variable to the directory containing the prompt files
os.environ['PDD_PATH'] = './'

# Define the inputs for the function
unit_test = """
def test_addition():
    assert add(1, 2) == 4  # This test is expected to fail
"""

code = """
def add(a, b):
    return a + b
"""

error = "AssertionError: assert 3 == 4"
strength = 0.8  # Adjust the strength as needed

# Call the function to fix errors from unit tests
updated_unit_test, updated_code, fixed_unit_test, fixed_code = fix_errors_from_unit_tests(unit_test, code, error, strength)

# Print the results
print("Updated Unit Test:")
print(updated_unit_test)
print("\nUpdated Code:")
print(updated_code)
print("\nFixed Unit Test:")
print(fixed_unit_test)
print("\nFixed Code:")
print(fixed_code)
# ```

# ### Input Parameters
# - `unit_test` (str): The unit test code that is failing.
# - `code` (str): The original code that the unit test is testing.
# - `error` (str): The error message generated by the failing unit test.
# - `strength` (float): A value between 0 and 1 that indicates the strength of the model's suggestions.

# ### Output Parameters
# - Returns a tuple containing:
#   - `updated_unit_test` (str): The modified unit test code after applying fixes.
#   - `updated_code` (str): The modified code after applying fixes.
#   - `fixed_unit_test` (str): The final version of the unit test code.
#   - `fixed_code` (str): The final version of the code.

# ### Note
# Make sure to replace `'path/to/your/prompts'` with the actual path to your prompt files. This example assumes that the `fix_errors_from_unit_tests.py` module is located in the `staging/pdd` directory relative to the script.
