// ── Colors ──────────────────────────────────────────────
export const COLORS = {
  background: '#000000',
  leftPanelBg: '#0F172A',
  rightPanelBg: '#0A0F1A',
  splitLine: '#334155',
  fileHeaderBg: '#1E293B',
  fileNameColor: '#4A90D9',
  lineNumberColor: '#64748B',
  codeTextColor: '#CBD5E1',
  leftAccent: '#D9944A',
  rightAccent: '#5AAA6E',
  testCheckColor: '#5AAA6E',
  terminalCommandColor: '#94A3B8',
  codeOutputColor: '#94A3B8',
  bottomLabelColor: '#E2E8F0',
  terminalBg: '#0F172A',
} as const;

// ── Dimensions ──────────────────────────────────────────
export const CANVAS_WIDTH = 1920;
export const CANVAS_HEIGHT = 1080;
export const SPLIT_X = 960;
export const PANEL_WIDTH = 958;
export const LINE_HEIGHT = 16;
export const FILE_HEADER_HEIGHT = 30;
export const GUTTER_WIDTH = 40;
export const TERMINAL_HEIGHT = 300;
export const TOTAL_FRAMES = 420;

// ── Dense prompt lines (left panel, 50 lines) ──────────
export const DENSE_PROMPT_LINES: string[] = [
  '# Parser v1 — Full Specification',
  '',
  'Parse user IDs from untrusted input.',
  'Input may be a string, bytes, or None.',
  'Always validate before processing.',
  '',
  '## Null Handling',
  'Handle null input by returning None.',
  'Handle empty string by returning None.',
  'Handle whitespace-only by returning None.',
  'If input is bytes, decode as UTF-8 first.',
  'If decode fails, return None.',
  '',
  '## ID Format',
  'Valid IDs match: [a-zA-Z0-9_-]{3,64}',
  'For unicode characters, normalize to NFC',
  'before validation. Strip zero-width chars.',
  'Reject any ID containing control characters.',
  'Reject IDs starting with a hyphen.',
  'Reject IDs that are all numeric.',
  '',
  '## Unicode Edge Cases',
  'Normalize combining characters (é → é).',
  'Strip BOM markers from start of input.',
  'Handle surrogate pairs in UTF-16 input.',
  'Reject private-use Unicode characters.',
  '',
  '## Error Conditions',
  'ValueError for malformed ID strings.',
  'TypeError if input is not str/bytes/None.',
  'Never raise on network-originated input.',
  'Log all validation failures to stderr.',
  'Include original input (truncated to 100',
  'chars) in error messages for debugging.',
  '',
  '## Performance Constraints',
  'Must process 10k IDs in < 100ms.',
  'Pre-compile regex patterns at module load.',
  'Use __slots__ for any wrapper objects.',
  'Avoid allocations in the hot path.',
  'Cache normalized forms (LRU, size=1024).',
  '',
  '## Return Contract',
  'Return type: Optional[str], never throw.',
  'Return normalized form, not original input.',
  'Returned IDs are always lowercase.',
  'Returned IDs are always NFC-normalized.',
  'Strip trailing whitespace from result.',
  'Guarantee: len(result) <= 64 if not None.',
  '# End of specification.',
];

// ── Minimal prompt lines (right panel, 10 lines) ───────
export const MINIMAL_PROMPT_LINES: string[] = [
  '# Parser v2 — Intent Only',
  '',
  'Parse user IDs from untrusted input.',
  '',
  'Return None on failure, never throw.',
  '',
  'Handle unicode (normalize NFC).',
  '',
  'Latency < 100ms for batch of 10k.',
  '',
];

// ── Test results (47 tests) ────────────────────────────
export const TEST_RESULTS: string[] = [
  'test_parse_valid_id',
  'test_parse_uppercase_id',
  'test_parse_with_hyphens',
  'test_parse_with_underscores',
  'test_null_input',
  'test_empty_string',
  'test_whitespace_only',
  'test_bytes_input_utf8',
  'test_bytes_input_invalid',
  'test_unicode_nfc',
  'test_unicode_combining',
  'test_unicode_bom_strip',
  'test_unicode_surrogate',
  'test_unicode_private_use',
  'test_zero_width_chars',
  'test_control_characters',
  'test_id_too_short',
  'test_id_too_long',
  'test_id_starts_with_hyphen',
  'test_id_all_numeric',
  'test_id_special_chars',
  'test_id_with_spaces',
  'test_regex_pattern_match',
  'test_case_normalization',
  'test_trailing_whitespace',
  'test_type_error_int',
  'test_type_error_list',
  'test_type_error_dict',
  'test_value_error_malformed',
  'test_error_logging_stderr',
  'test_error_msg_truncation',
  'test_no_raise_network_input',
  'test_batch_10k_under_100ms',
  'test_regex_precompiled',
  'test_slots_usage',
  'test_hot_path_no_alloc',
  'test_lru_cache_size',
  'test_lru_cache_eviction',
  'test_return_type_optional',
  'test_return_normalized_form',
  'test_return_lowercase',
  'test_return_nfc_normalized',
  'test_return_stripped',
  'test_return_max_length',
  'test_idempotent_parse',
  'test_concurrent_access',
  'test_deterministic_output',
];

// ── Generated code (identical for both panels) ─────────
export const GENERATED_CODE_LINES: string[] = [
  'def parse_user_id(raw: str | bytes | None) -> str | None:',
  '    if raw is None: return None',
  '    text = raw.decode("utf-8") if isinstance(raw, bytes) else raw',
  '    normalized = unicodedata.normalize("NFC", text.strip())',
  '    return normalized.lower() if ID_RE.match(normalized) else None',
];
