import React from "react";
import { AbsoluteFill } from "remotion";
import {
  CODE_TEXT_COLOR,
  CODE_KEYWORD_COLOR,
  CODE_STRING_COLOR,
  CODE_FUNCTION_COLOR,
  CODE_TYPE_COLOR,
  CODE_COMMENT_COLOR,
  CODE_PARAM_COLOR,
} from "./constants";

/**
 * Static code underlay representing regenerated TypeScript code.
 * Rendered at low opacity as visual texture behind the title card.
 */

interface CodeToken {
  text: string;
  color: string;
}

interface CodeLine {
  indent: number;
  tokens: CodeToken[];
}

const CODE_LINES: CodeLine[] = [
  {
    indent: 0,
    tokens: [
      { text: "// UserService.ts — regenerated by pdd", color: CODE_COMMENT_COLOR },
    ],
  },
  { indent: 0, tokens: [] },
  {
    indent: 0,
    tokens: [
      { text: "import", color: CODE_KEYWORD_COLOR },
      { text: " { ", color: CODE_TEXT_COLOR },
      { text: "User", color: CODE_TYPE_COLOR },
      { text: ", ", color: CODE_TEXT_COLOR },
      { text: "ValidationResult", color: CODE_TYPE_COLOR },
      { text: " } ", color: CODE_TEXT_COLOR },
      { text: "from", color: CODE_KEYWORD_COLOR },
      { text: " ", color: CODE_TEXT_COLOR },
      { text: "'./types'", color: CODE_STRING_COLOR },
      { text: ";", color: CODE_TEXT_COLOR },
    ],
  },
  { indent: 0, tokens: [] },
  {
    indent: 0,
    tokens: [
      { text: "export", color: CODE_KEYWORD_COLOR },
      { text: " ", color: CODE_TEXT_COLOR },
      { text: "function", color: CODE_KEYWORD_COLOR },
      { text: " ", color: CODE_TEXT_COLOR },
      { text: "processUserData", color: CODE_FUNCTION_COLOR },
      { text: "(", color: CODE_TEXT_COLOR },
      { text: "input", color: CODE_PARAM_COLOR },
      { text: ": ", color: CODE_TEXT_COLOR },
      { text: "User", color: CODE_TYPE_COLOR },
      { text: "): ", color: CODE_TEXT_COLOR },
      { text: "ValidationResult", color: CODE_TYPE_COLOR },
      { text: " {", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 2,
    tokens: [
      { text: "const", color: CODE_KEYWORD_COLOR },
      { text: " normalized = ", color: CODE_TEXT_COLOR },
      { text: "normalizeEmail", color: CODE_FUNCTION_COLOR },
      { text: "(input.email);", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 2,
    tokens: [
      { text: "const", color: CODE_KEYWORD_COLOR },
      { text: " validated = ", color: CODE_TEXT_COLOR },
      { text: "validateAge", color: CODE_FUNCTION_COLOR },
      { text: "(input.age);", color: CODE_TEXT_COLOR },
    ],
  },
  { indent: 0, tokens: [] },
  {
    indent: 2,
    tokens: [
      { text: "if", color: CODE_KEYWORD_COLOR },
      { text: " (!validated.ok) {", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 4,
    tokens: [
      { text: "return", color: CODE_KEYWORD_COLOR },
      { text: " { ", color: CODE_TEXT_COLOR },
      { text: "success", color: CODE_PARAM_COLOR },
      { text: ": ", color: CODE_TEXT_COLOR },
      { text: "false", color: CODE_KEYWORD_COLOR },
      { text: ", ", color: CODE_TEXT_COLOR },
      { text: "error", color: CODE_PARAM_COLOR },
      { text: ": validated.message };", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 2,
    tokens: [{ text: "}", color: CODE_TEXT_COLOR }],
  },
  { indent: 0, tokens: [] },
  {
    indent: 2,
    tokens: [
      { text: "return", color: CODE_KEYWORD_COLOR },
      { text: " {", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 4,
    tokens: [
      { text: "success", color: CODE_PARAM_COLOR },
      { text: ": ", color: CODE_TEXT_COLOR },
      { text: "true", color: CODE_KEYWORD_COLOR },
      { text: ",", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 4,
    tokens: [
      { text: "data", color: CODE_PARAM_COLOR },
      { text: ": { ...input, ", color: CODE_TEXT_COLOR },
      { text: "email", color: CODE_PARAM_COLOR },
      { text: ": normalized },", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 2,
    tokens: [{ text: "};", color: CODE_TEXT_COLOR }],
  },
  {
    indent: 0,
    tokens: [{ text: "}", color: CODE_TEXT_COLOR }],
  },
  { indent: 0, tokens: [] },
  {
    indent: 0,
    tokens: [
      { text: "function", color: CODE_KEYWORD_COLOR },
      { text: " ", color: CODE_TEXT_COLOR },
      { text: "normalizeEmail", color: CODE_FUNCTION_COLOR },
      { text: "(", color: CODE_TEXT_COLOR },
      { text: "email", color: CODE_PARAM_COLOR },
      { text: ": ", color: CODE_TEXT_COLOR },
      { text: "string", color: CODE_TYPE_COLOR },
      { text: "): ", color: CODE_TEXT_COLOR },
      { text: "string", color: CODE_TYPE_COLOR },
      { text: " {", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 2,
    tokens: [
      { text: "return", color: CODE_KEYWORD_COLOR },
      { text: " email.", color: CODE_TEXT_COLOR },
      { text: "trim", color: CODE_FUNCTION_COLOR },
      { text: "().", color: CODE_TEXT_COLOR },
      { text: "toLowerCase", color: CODE_FUNCTION_COLOR },
      { text: "();", color: CODE_TEXT_COLOR },
    ],
  },
  {
    indent: 0,
    tokens: [{ text: "}", color: CODE_TEXT_COLOR }],
  },
];

interface CodeUnderlayProps {
  opacity: number;
}

export const CodeUnderlay: React.FC<CodeUnderlayProps> = ({ opacity }) => {
  return (
    <AbsoluteFill
      style={{
        opacity,
        padding: "80px 120px",
        fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
        fontSize: 13,
        lineHeight: 1.7,
      }}
    >
      {CODE_LINES.map((line, i) => (
        <div key={i} style={{ paddingLeft: line.indent * 16, minHeight: 22 }}>
          {line.tokens.map((token, j) => (
            <span key={j} style={{ color: token.color }}>
              {token.text}
            </span>
          ))}
        </div>
      ))}
    </AbsoluteFill>
  );
};
