steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', '${_AR_IMAGE}']
    allowFailure: true
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from=${_AR_IMAGE}'
      - '-t'
      - '${_AR_IMAGE}'
      - '-f'
      - 'ci/cloud-batch/Dockerfile'
      - '.'
images:
  - '${_AR_IMAGE}'
options:
  machineType: 'E2_HIGHCPU_8'
substitutions:
  _AR_IMAGE: 'us-central1-docker.pkg.dev/prompt-driven-development-stg/pdd-ci/pdd-test:latest'
timeout: '1200s'
